### ISSUE TITLE
No esta la barra de administración

### ISSUE THREAD

**Issue by fabiankoliren** [dsebao/simpledashboard#1]
Al instalar el plugin se pierde la barra negra superior de administración. Por esto se pierde la opción de volver a la página y cerrar sesión. 
Sino esta por cuestiones estéticas habría que ver donde incluir estas opciones del menú

**Comment by dsebao** [comment]
Si bien el menu superior lo saque deje la opcion de salir de la sesion y ver pagina fijate que estan presentes en el menu.

**Comment by dsebao** [comment]
Actualizado algunos links en el sidebar para tener acceso a ver sitio y logout
